### ISSUE TITLE
Should MIP7 be amended to include Operational Support Domain?

### ISSUE THREAD

**Issue by Davidutro** [sky-ecosystem/mips#148]
I see two camps of Domain teams forming, as implied by the MIPs.

1. Domain Teams required for Collateral Onboarding (`MIP 07`)
Risk, Oracles, Smart Contracts, Legal

2. Other Domain Teams (Individual, seperate MIPs?)
Operational Support and Governance Communications.

Is this something that we are being mindful about? 

In addition to the Domain Teams being listed on `MIP07`, I saw that Domain Facilitators get onboarded through `MIP07c3`
ex: [MIP7c3-SP5: Seb Risk Team](https://forum.makerdao.com/t/mip7c3-sp5-domain-team-onboarding-risk-domain-team/5476) & [MIP7c3-SP6: SamM Smart Contracts](https://forum.makerdao.com/t/mip7c3-sp6-domain-team-onboarding-smart-contracts-domain-team/5559)

While the Operational Support Domain is only present in MIP28, and uses `MIP28c7` for onboarding Operational Support Domain Team Facilitators
ex: [MIP28c7-SP2: Juan Operational Support](https://forum.makerdao.com/t/mip28c7-sp2-subproposal-for-operational-support-domain-facilitator-onboarding/5309)

Is this right? Do you think this structure makes sense? @amy-jung @CPSTL @LongForWisdom @juan-fintech

If something like a Governance Communications Domain Team forms, will it also have it's own separate MIP to house the definition and onboarding/offboarding proposals?

**Comment by juan-fintech** [comment]
We probably need to amend a couple of MIPs soon. Depending on how we decentralize. 

Short answer is 'yes'; good spot, @Davidutro

**Comment by amy-jung** [comment]
So MIP7 was originally built specific to collateral onboarding. 

[MIP23](https://github.com/makerdao/mips/blob/Accepted/MIP23/mip23.md) was accepted and domains were supposed to replace their MIP7 with the template provided in MIP23. Since there was discussion around a MIP that would replaced or be amended by a new framework, it wasn't done. Now there may be a newer MIP replacing/amending, therefore it's again on pause so facilitators don't have to rewrite again.

Operational Support was built with MIP23 in mind, which is why it follows that template. So my answer is no.

**Comment by Davidutro** [comment]
Got it, that's super insightful.

What you wrote makes sense to me now that I've seen Juan's proposed [Operating Model and MIP set](https://forum.makerdao.com/t/road-to-dao-the-core-unit-operating-model/6105)

I am closing this issue for now then since this is on pause and it looks like there will be some time before it's formally submitted.
